import type { TemplateMeta, TemplateSlug } from '../domain/types'

/** The date every repository figure below was read from the GitHub REST API. */
const AS_OF = '2026-09-10'

/**
 * Index order: the template this site runs on first, then by usage signal.
 * Together the five cover one template per delivery target — a Next.js
 * full-stack app, a React Native mobile app, a Vite single-page client, a
 * Python serverless backend and a Node backend.
 */
export const templateMeta: readonly TemplateMeta[] = [
  {
    slug: 'next-stack',
    name: 'next-stack',
    repository: 'https://github.com/Jdavid0610/next-stack',
    homepage: 'https://next-stack-phi.vercel.app',
    programmingLanguage: 'TypeScript',
    runtimePlatform: 'Node.js',
    stars: 1,
    forks: 0,
    created: '2026-09-10',
    lastPush: '2026-09-10',
    asOf: AS_OF,
    license: null,
    poweringThisSite: true,
    tags: [
      'Next.js',
      'React',
      'TypeScript',
      'App Router',
      'Server rendering',
      'Drizzle ORM',
      'PostgreSQL',
      'better-auth',
      'RBAC',
      'TanStack Query',
      'Zod',
      'Tailwind CSS',
      'schema-dts',
      'Vitest',
      'Playwright',
      'Internationalization',
    ],
  },
  {
    slug: 'react-native-expo-stack',
    name: 'react-native-expo-stack',
    repository: 'https://github.com/Jdavid0610/react-native-expo-stack',
    programmingLanguage: 'TypeScript',
    runtimePlatform: 'React Native',
    stars: 5,
    forks: 0,
    created: '2026-02-09',
    lastPush: '2026-06-27',
    asOf: AS_OF,
    license: null,
    relatedProjectSlug: 'herbafit',
    tags: [
      'React Native',
      'Expo',
      'Expo Router',
      'React',
      'TypeScript',
      'TanStack Query',
      'Zustand',
      'react-hook-form',
      'Zod',
      'NativeWind',
      'Reanimated',
      'MMKV',
      'Axios',
    ],
  },
  {
    slug: 'vite-stack',
    name: 'vite-stack',
    repository: 'https://github.com/Jdavid0610/vite-stack',
    programmingLanguage: 'TypeScript',
    runtimePlatform: 'Browser',
    stars: 4,
    forks: 1,
    created: '2025-04-25',
    lastPush: '2026-07-23',
    asOf: AS_OF,
    license: null,
    tags: [
      'React',
      'Vite',
      'TypeScript',
      'React Router',
      'TanStack Query',
      'Zustand',
      'react-hook-form',
      'Zod',
      'Tailwind CSS',
      'Axios',
      'pnpm',
    ],
  },
  {
    slug: 'fastapi-lambda-cdk-template',
    name: 'fastapi-lambda-cdk-template',
    repository: 'https://github.com/Jdavid0610/fastapi-lambda-cdk-template',
    programmingLanguage: 'Python',
    runtimePlatform: 'AWS Lambda',
    stars: 1,
    forks: 0,
    created: '2026-05-11',
    lastPush: '2026-05-11',
    asOf: AS_OF,
    license: null,
    relatedProjectSlug: 'talentu',
    tags: [
      'Python',
      'FastAPI',
      'Mangum',
      'AWS Lambda',
      'Amazon API Gateway',
      'AWS CDK',
      'Amazon DynamoDB',
      'PostgreSQL',
      'SQLAlchemy',
      'Alembic',
      'Pydantic',
      'Amazon SQS',
      'Amazon S3',
      'Amazon CloudFront',
      'AWS Systems Manager Parameter Store',
      'GitHub Actions',
    ],
  },
  {
    slug: 'express-hexagonal',
    name: 'express-hexagonal',
    repository: 'https://github.com/Jdavid0610/express-hexagonal',
    programmingLanguage: 'TypeScript',
    runtimePlatform: 'Node.js',
    stars: 3,
    forks: 0,
    created: '2024-07-12',
    lastPush: '2024-12-01',
    asOf: AS_OF,
    license: null,
    tags: [
      'Express',
      'TypeScript',
      'Node.js',
      'Hexagonal architecture',
      'Sequelize',
      'PostgreSQL',
      'Swagger UI',
      'Docker',
    ],
  },
]

export const templateSlugs: readonly TemplateSlug[] = templateMeta.map(
  (template) => template.slug,
)
