import { siteConfig } from '@/shared/config/site'
import { locales, type Locale } from '@/shared/i18n/config'
import { formatMonth } from '@/shared/lib/format'
import { education, getProfile } from '@/modules/profile/content'
import { getExperienceCopy, getRoles } from '@/modules/experience/content'
import { getProjects, getProjectsCopy } from '@/modules/projects/content'
import { getOpenSourceCopy, getTemplates } from '@/modules/open-source/content'
import { getFaq } from '@/modules/faq/content'
import { getPosts } from '@/modules/blog/content'

/**
 * Where `llms.txt` is a map, `llms-full.txt` is the territory: the complete
 * prose of the site as plain text, so a model with one fetch has the whole
 * corpus and never needs to render a page.
 *
 * It is generated by walking the same typed content that renders the site,
 * never hand-written, so it cannot drift from the pages it describes.
 */
export const dynamic = 'force-static'

function section(lines: string[], title: string) {
  lines.push('')
  lines.push('='.repeat(72))
  lines.push(title)
  lines.push('='.repeat(72))
  lines.push('')
}

function localeBlock(lines: string[], locale: Locale) {
  const profile = getProfile(locale)
  const experienceCopy = getExperienceCopy(locale)
  const roles = getRoles(locale)
  const projectsCopy = getProjectsCopy(locale)
  const projects = getProjects(locale)
  const openSourceCopy = getOpenSourceCopy(locale)
  const templates = getTemplates(locale)
  const faq = getFaq(locale)
  const posts = getPosts(locale)

  section(lines, `LOCALE: ${locale}`)

  lines.push(`## Biography (${locale})`)
  lines.push('')
  lines.push(profile.longBio.join('\n\n'))
  lines.push('')
  lines.push(`Positioning: ${profile.positioning.statement}`)
  for (const pillar of profile.positioning.pillars) {
    lines.push(`- ${pillar.title}: ${pillar.description}`)
  }
  lines.push('')
  lines.push(`Education: ${profile.education.summary}`)
  lines.push('')

  lines.push(`## Experience (${locale})`)
  lines.push('')
  lines.push(experienceCopy.overlapNote)
  lines.push('')
  for (const role of roles) {
    const end = role.end ?? ''
    lines.push(`### ${role.title}, ${role.employer}`)
    lines.push(
      `Dates: ${role.start} to ${end || 'present'} (${formatMonth(role.start, locale)} – ${role.end ? formatMonth(role.end, locale) : experienceCopy.presentLabel})`,
    )
    lines.push(`Location: ${role.location}`)
    lines.push(`Type: ${experienceCopy.bucketLabels[role.bucket]}`)
    lines.push(role.summary)
    for (const achievement of role.achievements) lines.push(`- ${achievement}`)
    if (role.technologies.length > 0) {
      lines.push(`Technology: ${role.technologies.join(', ')}`)
    }
    lines.push('')
  }

  lines.push(`## Projects (${locale})`)
  lines.push('')
  for (const project of projects) {
    lines.push(`### ${project.name} (${project.slug})`)
    lines.push(`Type: ${projectsCopy.bucketLabels[project.bucket]}`)
    lines.push(`Status: ${projectsCopy.statusLabels[project.status]}`)
    lines.push(`Role: ${project.role}`)
    for (const link of project.links) {
      lines.push(`${projectsCopy.linkLabels[link.key]}: ${link.href}`)
    }
    lines.push(project.definition)
    lines.push('')
    lines.push(`${projectsCopy.sectionLabels.problem}: ${project.problem}`)
    lines.push('')
    lines.push(`${projectsCopy.sectionLabels.contribution}: ${project.contribution}`)
    lines.push('')
    lines.push(`${projectsCopy.sectionLabels.features}:`)
    for (const feature of project.features) lines.push(`- ${feature}`)
    lines.push('')
    lines.push(`${projectsCopy.sectionLabels.stack}: ${project.stack.join(', ')}`)
    lines.push('')
    lines.push(project.narrative.join('\n\n'))
    if (project.note) {
      lines.push('')
      lines.push(`Note: ${project.note}`)
    }
    lines.push('')
  }

  lines.push(`## Open-source templates (${locale})`)
  lines.push('')
  lines.push(openSourceCopy.indexIntro)
  lines.push('')
  for (const template of templates) {
    lines.push(`### ${template.name}`)
    lines.push(`Repository: ${template.repository}`)
    lines.push(
      `${template.programmingLanguage}, ${template.stars} stars, created ${template.created}, last push ${template.lastPush}, figures as of ${template.asOf}.`,
    )
    lines.push(`License: ${template.license ?? openSourceCopy.labels.noLicense}`)
    lines.push(template.definition)
    lines.push('')
    lines.push(`${openSourceCopy.labels.includes}:`)
    for (const item of template.includes) lines.push(`- ${item}`)
    lines.push('')
    lines.push(`${openSourceCopy.labels.tags}: ${template.tags.join(', ')}`)
    lines.push('')
    lines.push(template.narrative.join('\n\n'))
    lines.push('')
    lines.push(`${openSourceCopy.labels.maintenance}: ${template.maintenance}`)
    if (template.note) {
      lines.push('')
      lines.push(`Note: ${template.note}`)
    }
    lines.push('')
  }

  lines.push(`## Skills (${locale})`)
  lines.push('')
  for (const group of profile.skillGroups) {
    lines.push(`${profile.categoryLabels[group.key]}:`)
    for (const skill of group.skills) {
      const note = skill.note ? ` — ${skill.note}` : ''
      lines.push(`- ${skill.name} (${profile.tierLabels[skill.tier]})${note}`)
    }
    lines.push('')
  }
  lines.push(`${profile.tierLabels.listed}: ${profile.alsoListed.join(', ')}`)
  lines.push(profile.alsoListedNote)
  lines.push('')

  lines.push(`## Questions and answers (${locale})`)
  lines.push('')
  for (const entry of faq) {
    lines.push(`Q: ${entry.question}`)
    lines.push(`A: ${entry.answer}`)
    lines.push('')
  }

  if (posts.length > 0) {
    lines.push(`## Blog posts (${locale})`)
    lines.push('')
    for (const post of posts) {
      lines.push(`### ${post.title}`)
      lines.push(`Published: ${post.publishedAt}`)
      lines.push(post.description)
      lines.push('')
      for (const block of post.blocks) {
        if (block.type === 'heading') lines.push(`#### ${block.text}`)
        else if (block.type === 'list') for (const item of block.items) lines.push(`- ${item}`)
        else lines.push(block.text)
        lines.push('')
      }
    }
  }
}

function body(): string {
  const profile = getProfile('en')
  const lines: string[] = []

  lines.push(`# ${siteConfig.fullName} — full site text`)
  lines.push('')
  lines.push(profile.oneLineBio)
  lines.push(`Canonical URL: ${siteConfig.url}`)
  lines.push(`Contact: ${siteConfig.email} · ${siteConfig.phone.display}`)
  lines.push(`Education: ${profile.education.degree}, ${education.institution}`)
  lines.push('')
  lines.push(
    'This document is generated from the same typed content that renders the site, so it cannot drift from the pages it describes. Every locale served is included in full.',
  )
  lines.push(`Locales: ${locales.join(', ')}.`)

  for (const locale of locales) localeBlock(lines, locale)

  return lines.join('\n')
}

export function GET() {
  return new Response(body(), {
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'public, max-age=3600',
    },
  })
}
